# Generated by Django 4.0.6 on 2022-08-30 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='token',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
